
on:
  push:
    branches: [ "build_action" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: build_action
    - name: cd into folder
      run: cd Builds/LinuxMakefile
    - name: ls
      run: ls
    - name: make
      run: make Makefile
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
