
on:
  push:
    branches: [ "build_action" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: sudo apt-get install alsa-lib libcurl4-openssl-dev libwebkit2gtk-4.0 
    - uses: actions/checkout@v3
      with:
        ref: build_action
    - name: ls
      run: ls
    - name: make
      working-directory: ./Builds/LinuxMakefile
      run: |
        make clean
